archive:
  name: F-Droid arhīvs
  description: Oficiālās F-Droid brīvās programmatūras glabātavas arhīvs. Šeit esošās lietotnes ir vecas un var saturēt zināmas ievainojamības un drošības nepilnības.
repo:
  description: Oficiālā F-Droid brīvās programmatūras glabātava. Viss šeit tiek vienmēr būvēts no pirmkoda.
  name: F-Droid
