Ads:
  description: โปรแกรมนี้มีโฆษณา
  name: โฆษณา
DisabledAlgorithm:
  description: แอปนี้มีลายเซ็นความปลอดภัยที่ไม่รัดกุม
  name: ลงนามโดยใช้อัลกอริทึมที่ไม่ปลอดภัย
KnownVuln:
  name: ช่องโหว่ที่ทราบ
  description: แอปนี้มีช่องโหว่ด้านความปลอดภัยที่ทราบแล้ว
NSFW:
  name: มีเนื้อหาโป๊เปื่อย
  description: แอปนี้มีเนื้อหาที่ไม่ควรเผยแพร่หรือมองเห็นได้ทุกที่
NoSourceSince:
  name: ซอร์สโค้ดไม่สามารถใช้งานได้อีกต่อไป และไม่สามารถอัปเดตได้
NonFreeAdd:
  description: โปรแกรมนี้สนับสนุนส่วนขยายที่ไม่เสรี
  name: ส่วนเสริมที่ไม่ฟรี
NonFreeAssets:
  description: โปรแกรมนี้มีส่วนประกอบภาพเสียงที่ไม่เสรี
  name: Assetsที่ไม่ฟรี
NonFreeDep:
  description: โปรแกรมนี้พึ่งพาโปรแกรมไม่เสรีอื่นๆ
  name: Dependenciesที่ไม่ฟรี
NonFreeNet:
  description: โปรแกรมนี้สนับสนุนการใช้งานบริการที่ไม่เสรี
  name: บริการเครือข่ายที่ไม่ฟรี
Tracking:
  description: แอปนี้ติดตามและรายงานกิจกรรมของคุณ
  name: การติดตาม
UpstreamNonFree:
  description: ซอร์สโค้ดต้นฉบับมีบางส่วนที่ไม่เสรี
  name: Upstream ที่ไม่ฟรี
TetheredNet:
  description: แอปนี้ส่งเสริมหรือขึ้นอยู่กับอินสแตนซ์ของบริการเครือข่ายทั้งหมด
  name: แชร์เน็ต
