Ads:
  description: Esta aplicación tiene publicidad
  name: Anuncios
DisabledAlgorithm:
  description: Esta aplicación tiene una firma de seguridad débil
  name: Firmado usando un algoritmo no seguro
KnownVuln:
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
  name: Vulnerabilidad conocida
NSFW:
  description: Esta app contiene contenido que no debería ser publicitado o visible en cualquier lugar
  name: NSFW
NoSourceSince:
  name: El código fuente ya no está disponible, no se puede actualizar.
NonFreeAdd:
  description: Esta aplicación promueve complementos no libres
  name: Complementos no libres
NonFreeAssets:
  description: Esta aplicación contiene recursos que no son libres
  name: Activos no libres
NonFreeDep:
  description: Esta aplicación depende de otras no libres
  name: Dependencias no libres
NonFreeNet:
  description: Esta aplicación promueve servicios de red que no son gratuitos
  name: Servicios de red no libres
Tracking:
  description: Esta aplicación rastrea e informa de su actividad
  name: Rastreo
UpstreamNonFree:
  description: El código fuente original no es totalmente libre
  name: Original no libre
TetheredNet:
  description: Esta aplicación depende enteramente de un determinado servicio de la red
  name: Servicios de red conectados
