Ads:
  description: Appen inneheld reklame
DisabledAlgorithm:
  description: Appen har ein svak tryggleikssignatur
KnownVuln:
  description: Appen inneheld eit kjent tryggleikshòl
NoSourceSince:
  name: Kjeldekoden er ikkje lenger tilgjengeleg, så det er ikkje mogleg med oppdatering.
NonFreeAdd:
  description: Appen marknadsfører ufrie tillegg
NonFreeAssets:
  description: Appen inneheld ufrie ressursar
NonFreeDep:
  description: Appen er avhengig av andre ufrie appar
NonFreeNet:
  description: Appen marknadsfører ufrie nett-tenester
Tracking:
  description: Denne appen sporar og rapporterer aktiviteten din
UpstreamNonFree:
  description: Kjeldekoden til oppstraums­appen er ikkje heilt fri
