Ads:
  description: Esta aplicación contén publicidade
  name: Anuncios
DisabledAlgorithm:
  description: Esta aplicación ten unha sinatura de seguranza feble
  name: Asinado usando un algoritmo inseguro
KnownVuln:
  description: Esta aplicación contén unha vulnerabilidade de seguranza coñecida
  name: Vulnerabilidade Coñecida
NSFW:
  description: Esta aplicación contén contido que non debe ser divulgado ou visíbel en todos os lugares
  name: NSFW
NoSourceSince:
  name: O código fonte xá non está dispoñíbel e non é posíbel a súa actualización.
NonFreeAdd:
  description: Esta aplicación promociona engadidos que non son libres ou de balde
  name: Complementos non libres
NonFreeAssets:
  description: Esta aplicación contén elemento non libres
  name: Activos non libres
NonFreeDep:
  description: Esta aplicación depende doutras aplicacións non libres
  name: Dependencias non libres
NonFreeNet:
  description: Esta aplicación promove servizos de rede que non son libres
  name: Servizos de rede non libres
Tracking:
  description: Esta aplicación rexistra e informa da túa actividade
  name: Seguimento
UpstreamNonFree:
  description: O código fonte non é completamente libre
  name: Código fonte non libre
