Ads:
  description: Ứng dụng này có quảng cáo
  name: Quảng cáo
DisabledAlgorithm:
  description: Ứng dụng này có chữ kí bảo mật yếu
  name: Được kí bằng thuật toán không an toàn
KnownVuln:
  description: Ứng dụng này có một lỗ hổng bảo mật đã biết
  name: Lỗ hổng bảo mật đã biết
NSFW:
  description: Ứng dụng này chứa nội dung không nên được công khai ở mọi nơi
  name: NSFW
NoSourceSince:
  name: Mã nguồn không còn nữa, không thể có cập nhật.
NonFreeAdd:
  description: Ứng dụng này khuyến khích các phần mở rộng không tự do
  name: Phần mở rộng không tự do
NonFreeAssets:
  description: Ứng dụng này có những phần không tự do
  name: Các phần không tự do
NonFreeDep:
  description: Ứng dụng này phụ thuộc vào các ứng dụng không tự do khác
  name: Phụ thuộc vào những thứ không tự do
NonFreeNet:
  description: Ứng dụng này khuyến khích các dịch vụ mạng không tự do
  name: Dịch vụ mạng không tự do
Tracking:
  description: Ứng dụng này theo dõi và báo cáo hoạt động của bạn
  name: Theo dõi
UpstreamNonFree:
  description: Mã nguồn không hoàn toàn tự do
  name: Dự án mẹ không tự do
