Ads:
  description: Este aplicativo contém anúncios
  name: Anúncios
DisabledAlgorithm:
  description: Este aplicativo tem uma assinatura de segurança fraca
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: Este aplicativo contém uma falha de segurança já conhecida
  name: Vulnerabilidade conhecida
NSFW:
  description: Este aplicativo contém conteúdo impróprio para menores de idade
  name: NSFW
NoSourceSince:
  name: Não é possível atualizar, o código fonte não está mais disponível.
NonFreeAdd:
  description: Este aplicativo promove complementos não livres
  name: Complementos não livres
NonFreeAssets:
  description: Este aplicativo contém conteúdo não livre
  name: Conteúdos não livres
NonFreeDep:
  description: Este aplicativo depende de aplicativos não livres
  name: Dependências não livres
NonFreeNet:
  description: Este app promove ou depende inteiramente em um serviço de rede não-livre
  name: Serviços de rede não livres
Tracking:
  description: Este aplicativo rastreia e relata sua atividade
  name: Rastreamento
UpstreamNonFree:
  description: O código fonte original não é totalmente livre
  name: Upstream não livre
TetheredNet:
  description: Este app depende inteiramente de uma determinada instância de um serviço de rede
  name: Serviços de rede vinculada
