repo:
  description: O repositório oficial de software livre do F-Droid. Tudo neste repositório é compilado do código-fonte.
  name: F-Droid
archive:
  description: O arquivo do repositório oficial de software livre do F-Droid. Os aplicativos aqui são antigos e podem conter vulnerabilidades conhecidas e problemas de segurança!
  name: Arquivo F-Droid
