Connectivity:
  name: Nascacht
Development:
  name: Forbairt
Games:
  name: Cluichí
Graphics:
  name: Grafaicí
Internet:
  name: Idirlíon
Reading:
  name: Léamh
Navigation:
  name: Loingseoireacht
Phone & SMS:
  name: Fón & SMS
Science & Education:
  name: Eolaíocht & Oideachas
Security:
  name: Slándáil
Sports & Health:
  name: Spóirt & Sláinte
System:
  name: Córas
Theming:
  name: Téamaí
Time:
  name: Am
Money:
  name: Airgead
Multimedia:
  name: Ilmheáin
Writing:
  name: Ag scríobh
