archive:
  name: Cartlann F-Droid
  description: Cartlann stór oifigiúil F-Droid Bogearraí Saor in Aisce. Tá aipeanna anseo sean agus is féidir leo leochaileachtaí agus ceisteanna slándála aitheanta a bheith iontu!
repo:
  description: An stór oifigiúil F-Droid Bogearraí Saor in Aisce. Tógtar gach rud sa stór seo ón gcód foinse i gcónaí.
  name: F-Droid
