Ads:
  description: Hierdie program bevat advertensies
DisabledAlgorithm:
  description: Hierdie app het \'n swak sekuriteitshandtekening
KnownVuln:
  description: Hierdie inligting bevat \'n bekende veiligheidskwesbaarheid
NoSourceSince:
  name: Die bronkode is nie meer beskikbaar nie, geen opdaterings moontlik nie.
NonFreeAdd:
  description: Hierdie program bevorder nie-vrye toevoegsels
NonFreeAssets:
  description: Hierdie program bevat nie-vrye bates
NonFreeDep:
  description: Hierdie program is afhanklik van ander nie-vrye programme
NonFreeNet:
  description: Hierdie program bevorder nie-vrye netwerk dienste
Tracking:
  description: Hierdie program speur op, en rapporteer jou aktiwiteite
UpstreamNonFree:
  description: Die stroomop bronkode is nie heeltemal vry nie
