Ads:
  description: Ta aplikacija vsebuje oglaševanje
  name: Oglasi
DisabledAlgorithm:
  description: Ta aplikacija ima šibek varnostni podpis
  name: Podpisano z nezaščitenim algoritmom
KnownVuln:
  description: Ta aplikacija vsebuje znano varnostno pomanjkljivost
  name: Znana ranljivost
NoSourceSince:
  name: Izvirna koda ni več na voljo, zato posodobitve niso možne.
NonFreeAdd:
  description: Ta aplikacija promovira plačljive dodatke
  name: Ne-prosti dodatki
NonFreeAssets:
  description: Ta aplikacija vsebuje neodprte enote
  name: Ne-prosta sredstva
NonFreeDep:
  description: Ta aplikcija je odvisna od ostalih ne odprtih aplikacijah
  name: Ne-proste odvisnosti
NonFreeNet:
  description: Ta aplikacija promovira plačljive internetne storitve
  name: Ne-prosti omrežne storitve
Tracking:
  description: Ta aplikacija vam sledi in poroča o vaši aktivnosti
  name: Sledenje
UpstreamNonFree:
  description: Originalna koda ni popolnoma odprta
  name: Ne-prost Upstream
