Ads:
  description: Tämä sovellus sisältää mainoksia
  name: Mainokset
DisabledAlgorithm:
  description: Tällä sovelluksella on heikko turvallisuusallekirjoitus
  name: Allekirjoitettu turvattomalla algoritmilla
KnownVuln:
  description: Tämä sovellus sisältää tunnetun haavoittuvuuden
  name: Tunnettu haavoittuvuus
NSFW:
  description: Sovelluksessa on sisältöä, jota ei tulisi julkaista tai näyttää kaikkialla
  name: NSFW
NoSourceSince:
  name: Lähdekoodi ei ole enää saatavilla, päivityksiä ei voi tehdä.
NonFreeAdd:
  description: Tämä sovellus suosittelee ei-vapaita lisäosia
  name: Ei-vapaat lisäosat
NonFreeAssets:
  description: Tämä sovellus sisältää ei-vapaita osia
  name: Ei-vapaa sisältö
NonFreeDep:
  description: Tämä sovellus on riippuvainen muista, ei-vapaista sovelluksista
  name: Ei-vapaat riippuvuudet
NonFreeNet:
  description: Tämä sovellus tukee tai on täysin riippuvainen ei-vapaasta verkkopalvelusta
  name: Ei-vapaat verkkopalvelut
Tracking:
  description: Tämä sovellus seuraa ja raportoi toimintaasi
  name: Seuranta
UpstreamNonFree:
  description: Upstream-lähdekoodi ei ole kokonaan vapaata
  name: Upstream ei-vapaa
TetheredNet:
  description: Tämä sovellus tukee tai on täysin riippuvainen tietystä verkkopalvelusta.
  name: TetheredNet
