Ads:
  description: App ino ine zvakashambadzwa zvemamwe makambani
NonFreeAdd:
  description: App inosesedza zvinowedzerwa paapp ino zvinobhadharwa
NonFreeAssets:
  description: App ino inenhumbi dzinobhadharwa
NonFreeDep:
  description: App ino inotemba nemamwe maapps anobhadharwa
NonFreeNet:
  description: App ino inosesedza zvirango zvemasaisai zvinobhadharwa
Tracking:
  description: App ino inotevera nekududzira zvauri kuita
UpstreamNonFree:
  description: Nyuko yemurau irikumberi haisi yemahara
