Ads:
  description: Dizze applikaasje hat advertinsjes
DisabledAlgorithm:
  description: Dizze applikaasje hat net in sterke feiligens 没ndertekening
KnownVuln:
  description: Dizze applikaasje hat in bekend feiligens probleem
NoSourceSince:
  name: De boarne koade is net langer beskikber, gjin fernijingen mooglik.
NonFreeAdd:
  description: Dizze applikaasje stimulearret it gebr没k fan net-frije add-ons
NonFreeDep:
  description: Dizze applikaasje hinget 么f fan oare net-frije applikaasjes
NonFreeNet:
  description: Dizze applikaasje stimulearret it gebr没k fan net-frije netwurk tsjinsten
Tracking:
  description: Dizze applikaasje folget en rapportearret jo aktiviteit
