Ads:
  description: Appen indeholder reklamer
  name: Reklamer
DisabledAlgorithm:
  description: Denne app har en svag sikkerhedssignatur
  name: Signeret med en usikker algoritme
KnownVuln:
  description: Denne app indeholder en kendt sårbarhed
  name: Kendt sårbarhed
NSFW:
  description: Denne app har et indhold som ikke bør publiceres eller være synlig overalt
  name: NSFW
NoSourceSince:
  name: Kildekoden er ikke længere tilgængelig; ingen opdateringer mulige.
NonFreeAdd:
  description: Appen fremmer ikke-frie tilføjelser
  name: Ikke frie tilføjelser
NonFreeAssets:
  description: Denne app indeholder ikke-frit indhold
  name: Ikke frie genstande
NonFreeDep:
  description: Denne app er afhængig af andre ikke-frie apps
  name: Ikke frie afhængigheder
NonFreeNet:
  description: Appen fremmer ikke-frie netværkstjenester
  name: Ikke-frie netværkstjenester
Tracking:
  description: Denne app sporer og indberetter din aktivitet
  name: Sporing
UpstreamNonFree:
  description: Opstrømskildekoden er ikke fuldstændig fri
  name: Ikke fri opstrøm
TetheredNet:
  description: Denne app afhænger helt af en bestemt instans af en netværkstjeneste
