Ads:
  description: Tiu ĉi aplikaĵo enhavas reklamojn
  name: Reklamoj
DisabledAlgorithm:
  description: Tiu ĉi aplikaĵo posedas malfortan sekurecan subskribon
  name: Subskribita per malsekura algoritmo
KnownVuln:
  description: Tiu ĉi aplikaĵo posedas sekurecan vundeblon
  name: Konata sekureca vundeblo
NSFW:
  description: Tiu ĉi aplikaĵo liveras enhavon, kiu ne estas taŭga por rigardi publike
  name: Maldeca enhavo
NoSourceSince:
  name: La fontkodo ne estas plu disponebla, neniu ebla ĝisdatigo.
NonFreeAdd:
  description: Tiu ĉi aplikaĵo favoras neliberajn aldonaĵojn
  name: Neliberaj aldonaĵoj
NonFreeAssets:
  description: Tiu ĉi aplikaĵo enhavas neliberan enhavon
  name: Nelibera enhavo
NonFreeDep:
  description: Tiu ĉi aplikaĵo dependas de aliaj neliberaj aplikaĵoj
  name: Neliberaj dependecoj
NonFreeNet:
  description: Tiu ĉi aplikaĵo favoras aŭ tute dependas de nelibera retservo
  name: Neliberaj retservoj
Tracking:
  description: Tiu ĉi aplikaĵo spuras kaj raportas vian agadon
  name: Spurado
UpstreamNonFree:
  description: La fontkodo ne estas tute libera
  name: Parte libera fontkodo
TetheredNet:
  description: Tiu ĉi aplikaĵo tute dependas de difinita ekzemplo de reta servo
  name: Alligita al retservo
