Ads:
  description: Mae\'r ap hwn yn cynnwys hysbysebion
DisabledAlgorithm:
  description: Mae gan yr ap hwn llofnod diogelwch wan
KnownVuln:
  description: Mae\'r ap hwn yn cynnwys gwendid diogelwch hysbys
NoSourceSince:
  name: Dyw\'r cod gwreiddiol ddim bellach ar gael a dim diweddariadau\'n bosib.
NonFreeAdd:
  description: Mae\'r ap hwn yn hyrwyddo ychwanegiadau sy\'n codi tâl
NonFreeAssets:
  description: Mae\'r ap hwn yn cynnwys asedau sydd am ddim
NonFreeDep:
  description: Mae\'r ap hwn yn dibynnu ar apiau eraill sy\'n codi tâl
NonFreeNet:
  description: Mae\'r ap hwn yn hyrwyddo gwasanaethau rhwydwaith sy\'n codi tâl
Tracking:
  description: Mae\'r ap hwn yn tracio ac adrodd dy weithgaredd
UpstreamNonFree:
  description: Dyw\'r cod uwchffrydio ddim yn gwbl am ddim
