Ads:
  description: Esta aplicación contiene publicidad
NonFreeAdd:
  description: Esta aplicación promueve complementos no gratuitos
NonFreeAssets:
  description: Esta aplicación contiene activos no libres
NonFreeDep:
  description: Esta aplicación depende de otras aplicaciones no gratuitas
NonFreeNet:
  description: Esta aplicación promueve servicios de red no gratuitos
Tracking:
  description: Esta aplicación realiza un seguimiento e informa de su actividad
UpstreamNonFree:
  description: El código fuente ascendente no es totalmente gratuito
