archive:
  name: Arxiu F-Droid
  description: L'arxiu del repositori oficial de programari lliure F-Droid. Les aplicacions aquí són antigues i poden contenir vulnerabilitats i problemes de seguretat coneguts!
repo:
  description: El repositori oficial de programari lliure F-Droid. Tot en aquest repositori sempre es construeix a partir del codi font.
  name: F-Droid
