Ads:
  description: دا کاریال انګروزي لري
DisabledAlgorithm:
  description: دا کاریال د خونديينې کمزوری لاسليک لري
NoSourceSince:
  name: سرچينې کوډ نور لاسلرلی نه دی، اوسمهالول شونې نه دي.
NonFreeAdd:
  description: دا کاریال ناازاده پر-زیاتوونې پرمخوړي
NonFreeAssets:
  description: دا کاریال ناازاده پانګې لري
NonFreeDep:
  description: دا کاریال په نورو ناازاده کاریالونو باندې اړه لري
NonFreeNet:
  description: دا کاریال ناازادې جال پالنې پرمخوړي
