Ads:
  description: ఈ అనువర్తనం ప్రకటనలు కలిగి ఉంది
  name: ప్రకటనలు
DisabledAlgorithm:
  description: ఈ అనువర్తనం బలహీన భద్రతా సంతకం కలిగి ఉంది
  name: సురక్షితం కాని అల్గోరిథం చే సైన్ చేయబడింది
KnownVuln:
  description: ఈ అనువర్తనం తెలిసిన భద్రతా దుర్బలత్వాన్ని కలిగి ఉంది
  name: తెలిసిన బలహీనత(vulnerability)
NSFW:
  name: చెడ్డ / అసభ్యకరమైన పదాలు లేదా విషయము.
  description: ఈ యాప్‌లో ప్రచారం చేయకూడని లేదా బయట కనిపించకూడని కంటెంట్ ఉంది
NoSourceSince:
  name: కొడ్ మూలం ఇక అందుబాటులో లేదు, నవికరణాలు లబించవు
NonFreeAdd:
  description: ఈ అనువర్తనం ఉచితం కానీ జోడింపులను ప్రోత్సహిస్తుంది
  name: '*Non-Free* కలయికలు'
NonFreeAssets:
  description: ఈ అనువర్తనం ఉచితం కానీ ఆస్తులను కలిగి ఉంది
  name: '*Non-Free* ఆస్తులు'
NonFreeDep:
  description: ఈ అనువర్తనం ఇతర ఉచితం కానీ అనువర్తనాలపై ఆధారపడి ఉంటుంది
  name: '*Non-Free* సాఫ్ట్వేర్ మీద ఆధారపడుతుంది'
NonFreeNet:
  description: ఈ అనువర్తనం ఉచితం కానీ నెట్వర్క్ సేవలను ప్రోత్సహిస్తుంది
Tracking:
  description: ఈ ఆప్ మీ కార్యకలాపాలను జాడించి నివేదిస్తుంది
  name: గమనిక చేయబడుతుంది
UpstreamNonFree:
  description: అప్స్ట్రీమ్ సోర్స్ కోడ్ పూర్తిగా ఉచితం కాదు
