Ads:
  description: Оваа апликација содржи реклами
  name: Реклами
DisabledAlgorithm:
  description: Оваа апликација има слаб безбедносен потпис
KnownVuln:
  description: Оваа апликација содржи позната безбедносна ранливост
NoSourceSince:
  name: Изворниот код повеќе не е достапен, не се можни ажурирања.
Tracking:
  description: Оваа апликација ја следи и јавува вашата активност
  name: Следење
