Ads:
  description: ဒီ app သည္ ေၾကျငာမ်ားပါဝင္သည္
  name: ကြော်ညာ
NonFreeAdd:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ေနာက္ထပ္ပါဝင္သည့္အရာမ်ားပါဝင္သည္
NonFreeAssets:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ပံုမ်ားပါဝင္သည္
  name: အခမဲ့မဟုတ်သော ပစ္စည်းများ
NonFreeDep:
  description: ဒီ app သည္ တျခားအခမဲ့မဟုတ္ေသာ app မ်ားေပၚမူတည္သည္
  name: အခမဲ့မဟုတ်သော မှီခိုမှုများ
NonFreeNet:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာကြန္ရက္ ဝန္ေဆာင္မႈကိုေထာက္ပံ့သည္
  name: အခမဲ့မဟုတ်သော ကွန်ရက်ဝန်ဆောင်မှုများ
Tracking:
  description: ဒီ app သည္ သင့္လႈပ္ရွားမႈမ်ားကိုလိုက္ၾကည့္ျပီးမွတ္တမ္း မွတ္သည္
UpstreamNonFree:
  description: ဆိုစ့္ကုဒ္သည္ လံုးဝအခမဲ့မဟုတ္ပါ
DisabledAlgorithm:
  description: ဤအက်ပ်မှာ လုံခြုံရေးအားနည်းသည့်လက္ခဏာများရှိသည်
  name: စိတ်ချရခြင်းမရှိသော အယ်လ်ဂိုလိုသမ်တစ်ခုဖြင့် sign လုပ်ထားသည်
KnownVuln:
  description: ဤအက်ပ်သည် လုံခြုံရေးချို့ယွင်းချက်တစ်ခုပါဝင်နေသည်
  name: အမျိုးအမည်သိသောချို့ယွင်းချက်
NSFW:
  description: ဤအက်ပ်၌ လူအများနှင့် ဆီလျော်ခြင်းမရှိသော အစိတ်အပိုင်းများပါဝင်သည်
  name: ညစ်ညမ်း
NoSourceSince:
  name: ရင်းမြစ်ကုဒ် မရှိသောကြောင့် အဆင့်မြှင့်တင်မှုများမရရှိနိုင်တော့ပါ။
