Ads:
  description: ဒီ app သည္ ေၾကျငာမ်ားပါဝင္သည္
NonFreeAdd:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ေနာက္ထပ္ပါဝင္သည့္အရာမ်ားပါဝင္သည္
NonFreeAssets:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာ ပံုမ်ားပါဝင္သည္
NonFreeDep:
  description: ဒီ app သည္ တျခားအခမဲ့မဟုတ္ေသာ app မ်ားေပၚမူတည္သည္
NonFreeNet:
  description: ဒီ app သည္ အခမဲ့မဟုတ္ေသာကြန္ရက္ ဝန္ေဆာင္မႈကိုေထာက္ပံ့သည္
Tracking:
  description: ဒီ app သည္ သင့္လႈပ္ရွားမႈမ်ားကိုလိုက္ၾကည့္ျပီးမွတ္တမ္း မွတ္သည္
UpstreamNonFree:
  description: ဆိုစ့္ကုဒ္သည္ လံုးဝအခမဲ့မဟုတ္ပါ
