Ads:
  description: Apu hili lina matangazo
  name: Matangazo
DisabledAlgorithm:
  description: Apu hii ina saini dhaifu ya usalama
  name: Imesainiwa kutumia Algorithimu isiyo salama
KnownVuln:
  description: Apu hii ina athari inayojulikana ya usalama
  name: Udhaifu unaojulikana
NSFW:
  description: Apu hii ina maudhui ambayo hayafai kutangazwa au kuonekana kila mahali
  name: NSFW
Tracking:
  name: Fuatilia
  description: Apu hii hufuatilia na kuripoti shughuli yako
NoSourceSince:
  name: Msimbo chanzo hio haipatikani tena, hakuna masasisho yanayowezekana.
NonFreeAdd:
  description: Apu hii inakuza nyongeza isiyo bure
  name: Nyongeza isiyo bure
NonFreeAssets:
  description: Apu hii ina raslimali isiyo bure
  name: Raslimali isiyo bure
NonFreeDep:
  description: Apu hii inategemea apu zingine zisizo bure
  name: Vitegemezi visivyo bure
NonFreeNet:
  description: Apu hii hukuza au hutegemea kabisa huduma ya mtandao isiyo bure
  name: Huduma ya mtandao isiyo bure
TetheredNet:
  description: Apu hii hutegemea kabisa mfano fulani wa huduma ya mtandao
  name: Huduma za Mtandao zilizounganishwa
UpstreamNonFree:
  description: Msimbo wa chanzo cha mkondo wa juu sio bure kabisa
  name: Mkondo wa juu usio bure
