Money:
  name: Pesa
Graphics:
  name: Michoro
Phone & SMS:
  name: Simu na Huduma ya Ujumbe Fupi
Science & Education:
  name: Sayansi na Elimu
Security:
  name: Usalama
Sports & Health:
  name: Michezo na Afya
Time:
  name: Saa
Connectivity:
  name: Muunganisho
Development:
  name: Maendeleo
Games:
  name: Michezo
Internet:
  name: Mtandao
Multimedia:
  name: Multimedia
Navigation:
  name: Urambazaji
Reading:
  name: Kusoma
System:
  name: Mfumo
Theming:
  name: Mandhari
Writing:
  name: Kuandika
