archive:
  description: Kumbukumbu hio ya ghala rasmi ya apu huru ya F-Droid. Apu hapa ni mzee na inaweza kuwa na udhaifu na masuala ya usalama!
  name: Kumbukumbu ya F-Droid
repo:
  description: Ghala rasmi la Programu huru ya F-Droid. Kila kitu katika ghala hili linajengwa kila mara kutoka kwa msimbo wa chanzo.
  name: F-Droid
