Connectivity:
  name: Conectividade
Development:
  name: Desenvolvimento
Games:
  name: Jogos
Graphics:
  name: Gráficos
Internet:
  name: Internet
Money:
  name: Finanças
Multimedia:
  name: Multimédia
Navigation:
  name: Navegação
Phone & SMS:
  name: Telefone e SMS
Reading:
  name: Leitura
Science & Education:
  name: Ciência e educação
Security:
  name: Segurança
Sports & Health:
  name: Desporto e saúde
System:
  name: Sistema
Theming:
  name: Temas
Time:
  name: Tempo
Writing:
  name: Escrita
