Ads:
  description: Ta aplikacja zawiera reklamy
  name: Reklamy
DisabledAlgorithm:
  description: Ta aplikacja ma słaby podpis bezpieczeństwa
  name: Podpisana przy użyciu niebezpiecznego algorytmu
KnownVuln:
  description: Ta aplikacja ma znaną podatność bezpieczeństwa
  name: Znana podatność
NSFW:
  description: Ta aplikacja zawiera treści, które nie powinny być publikowane ani widoczne wszędzie
  name: NSFW
NoSourceSince:
  name: Kod źródłowy nie jest już dostępny, nie są możliwe aktualizacje
NonFreeAdd:
  description: Ta aplikacja promuje niewolne dodatki
  name: Niewolne dodatki
NonFreeAssets:
  description: Ta aplikacja zawiera niewolne zasoby
  name: Niewolne zasoby
NonFreeDep:
  description: Ta aplikacja zależy od innych niewolnych aplikacji
  name: Niewolne zależności
NonFreeNet:
  description: Ta aplikacja promuje lub całkowicie zależy od niewolnej usługi sieciowej
  name: Niewolne usługi sieciowe
Tracking:
  description: Ta aplikacja śledzi i raportuje Twoją aktywność
  name: Śledzenie
UpstreamNonFree:
  description: Upstreamowy kod źródłowy nie jest w pełni wolny
  name: Niewolne upstream
TetheredNet:
  name: Usługi sieciowe wykorzystujące tethering
  description: Ta aplikacja całkowicie zależy od określonej instancji usługi sieciowej
