Connectivity:
  name: Connectivity
Development:
  name: Development
Games:
  name: Games
Graphics:
  name: Graphics
Internet:
  name: Internet
Money:
  name: Money
Multimedia:
  name: Multimedia
Phone & SMS:
  name: Phone & SMS
Navigation:
  name: Navigation
Reading:
  name: Reading
Science & Education:
  name: Science & Education
Time:
  name: Time
Security:
  name: Security
Sports & Health:
  name: Sports & Health
System:
  name: System
Theming:
  name: Theming
Writing:
  name: Writing
