Ads:
  description: Cette appli comprend des publicités
  name: Publicités
DisabledAlgorithm:
  description: La signature de sécurité de cette application est faible
  name: Signé par un algorithme non sécurisé
KnownVuln:
  description: Cette appli présente une vulnérabilité de sécurité connue
  name: Contient des vulnérabilités connues
NSFW:
  description: Cette application contient des contenus qui ne doivent pas être rendus publics ni visibles partout
  name: NSFW
NoSourceSince:
  name: Le code source n’est plus accessible, aucune mise à jour n’est possible.
NonFreeAdd:
  description: Cette application promeut des extensions qui ne sont pas libres
  name: Plugins non libres
NonFreeAssets:
  description: Cette appli comprend des éléments qui ne sont pas libres
  name: Composants non libres
NonFreeDep:
  description: Cette application s\'appuie d\'autres applications qui ne sont pas libres
  name: Dépendances payantes
NonFreeNet:
  description: Cette application dépends ou propose d'utiliser des services réseaux qui ne sont pas libres ou non modifiables.
  name: Services réseaux payants
Tracking:
  description: Cette application suit et transmet votre activité
  name: Traçage
UpstreamNonFree:
  description: Le code source en amont n’est pas entièrement libre
  name: Amont payant
TetheredNet:
  description: Cette application dépend entièrement d'un service réseau particulier
  name: Tethered Network Services
