diff --git a/build/android/Makefile b/build/android/Makefile
index 5fe0321b..06fc3769 100644
--- a/build/android/Makefile
+++ b/build/android/Makefile
@@ -503,6 +503,7 @@ irrlicht_download :
 		patch -p1 < ${ANDR_ROOT}/patches/irrlicht-touchcount.patch || exit 1;  \
 		patch -p1 < ${ANDR_ROOT}/patches/irrlicht-back_button.patch || exit 1; \
 		patch -p1 < ${ANDR_ROOT}/patches/irrlicht-texturehack.patch || exit 1; \
+		dos2unix ${ANDR_ROOT}/deps/irrlicht/source/Irrlicht/CEGLManager.cpp || exit 1; \
 		patch -p1 < ${ANDR_ROOT}/patches/irrlicht-native_activity.patch || exit 1; \
 	fi
 
