Ads:
  description: Esta aplicación tiene publicidad
DisabledAlgorithm:
  description: Esta aplicación tiene una firma de seguridad débil
KnownVuln:
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
NoSourceSince:
  name: El código fuente ya no está disponible, ninguna actualización posible.
NonFreeAdd:
  description: Esta aplicación promueve complementos no libres
NonFreeAssets:
  description: Esta aplicación contiene recursos no libres
NonFreeDep:
  description: Esta aplicación depende de otras aplicaciones no libres
NonFreeNet:
  description: Esta aplicación promueve servicios no libres
Tracking:
  description: Esta aplicación rastrea e informa de tu actividad
UpstreamNonFree:
  description: El codigo fuente de subida no es completamente libre
