Ads:
  description: Ova aplikacija sadržava oglase
DisabledAlgorithm:
  description: Ova aplikacija ima slab sigurnosni potpis
KnownVuln:
  description: Ova aplikacija sadrži poznatu sigurnosnu ranjivost
NoSourceSince:
  name: Izvorni kod više nije dostupan, nije moguće ažurirati.
NonFreeAdd:
  description: Ova aplikacija promovira neslobodne dodatke
NonFreeAssets:
  description: Ova aplikacija sadrži neslobodne resurse
NonFreeDep:
  description: Ova aplikacija ovisi o drugim neslobodnim aplikacijama
NonFreeNet:
  description: Ova aplikacija promovira neslobodne mrežne usluge
Tracking:
  description: Ova aplikacija prati i javlja Vašu aktivnost
UpstreamNonFree:
  description: Uzvodni izvorni kod nije u potpunosti otvoren/slobodan
