Ads:
  description: Asnas-a yegber adellel
DisabledAlgorithm:
  description: Asnas-a yesɛa azmul i ixuṣṣen deg tɣellist
NoSourceSince:
  name: Tangalt taɣbalut dayen ur telli ara, ulac ileqman.
NonFreeAdd:
  description: Asnas-a yegber Izegrar ur nelli ara d ilelliyen
NonFreeAssets:
  description: Asnas-a yegber iḥricen ur nelli ara d ilelliyen
NonFreeDep:
  description: Asnas-a icudd ɣer yisnasen-nniḍen ur nelli ara d ilelliyen
NonFreeNet:
  description: Asnas-a isnernay imeẓliyen n uẓeṭṭa ur nelli ara d ilelliyen
Tracking:
  description: Asnas-agi ad yeḍfeṛ udiγ ad d-yazen armud-ik
