#!/bin/bash -e

if [[ CI_PIPELINE_SOURCE == "merge_request_event" ]]; then
    curl --silent --request POST \
         --header "Private-Token: $PERSONAL_ACCESS_TOKEN" \
         --data "Thanks for your contribution!" \
         ${CI_API_V4_URL}/projects/${project_id}/merge_requests/$CI_MERGE_REQUEST_IID/notes
# insecure "captcha"
s=$((4`printf "$CI_COMMIT_SHA" | wc -c`-10))
e=$((s+`echo "$CI_SERVER_HOST" | wc -c`+18))
issuebot=`cat .issuebot | cut -b${s}-${e}`
project_id=36528

if test -z $CI_API_V4_URL; then
    echo CI_API_V4_URL is not set
    exit 1
elif test -z $CI_PIPELINE_ID; then
    echo CI_PIPELINE_ID is not set
    exit 1
fi

curl --silent --request POST \
     --form token=$issuebot \
     --form ref=master \
     --form "variables[FROM_CI_COMMIT_REF_NAME]=$CI_COMMIT_REF_NAME" \
     --form "variables[FROM_CI_COMMIT_REF_SLUG]=$CI_COMMIT_REF_SLUG" \
     --form "variables[FROM_CI_COMMIT_SHA]=$CI_COMMIT_SHA" \
     --form "variables[FROM_CI_JOB_ID]=$CI_JOB_ID" \
     --form "variables[FROM_CI_MERGE_REQUEST_IID]=$CI_MERGE_REQUEST_IID" \
     --form "variables[FROM_CI_PIPELINE_ID]=$CI_PIPELINE_ID" \
     --form "variables[FROM_CI_PROJECT_PATH]=$CI_PROJECT_PATH" \
     --form "variables[FROM_CI_PROJECT_URL]=$CI_PROJECT_URL" \
     ${CI_API_V4_URL}/projects/${project_id}/trigger/pipeline > logs/result.json \
    || echo "$0 failed to post to a merge request"
