Connectivity:
  name: Vernetzung
Development:
  name: Entwicklung
Games:
  name: Spiele
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Geld
Multimedia:
  name: Multimedia
Navigation:
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Lesen
Science & Education:
  name: Wissenschaft & Bildung
Security:
  name: Sicherheit
Sports & Health:
  name: Sport & Gesundheit
System:
  name: System
Theming:
  name: Aussehen
Time:
  name: Zeit
Writing:
  name: Schreiben
