Connectivity:
  name: Connettività
Development:
  name: Sviluppo
Games:
  name: Giochi
Graphics:
  name: Grafica
Internet:
  name: Internet
Money:
  name: Finanze
Multimedia:
  name: Multimedia
Navigation:
  name: Navigazione
Phone & SMS:
  name: Telefono e SMS
Reading:
  name: Lettura
Science & Education:
  name: Scienza ed educazione
Security:
  name: Sicurezza
Sports & Health:
  name: Sport e salute
System:
  name: Sistema
Theming:
  name: Personalizzazione
Time:
  name: Tempo
Writing:
  name: Scrittura
